name: proyecto_moviles2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase (Ãºltimas versiones estables)
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  pdf: ^3.6.0
  printing: ^5.6.0
  path_provider: ^2.0.11  
  # Otras dependencias
  intl: ^0.20.2
  image_picker: ^1.0.4
  flutter_local_notifications: ^19.2.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
